version: '3.8'
services:
  laravel:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - "8000:8000"
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: "1"
    volumes:
      - ./apps/laravel/:/var/www/html
    command: 'php artisan serve --host=0.0.0.0'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  symfony:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - "8001:8000"
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: "1"
    volumes:
      - ./apps/symfony/:/var/www/html
    command: 'php -S 0.0.0.0:8000 -t public'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  express:
    image: "node:20"
    working_dir: /home/node/app
    environment:
      - PORT=3000
    ports:
      - '8002:3000'
    volumes:
      - ./apps/express/:/home/node/app
    command: 'bash -c "npm install && npm run start"'
  nest:
    image: "node:20"
    working_dir: /home/node/app
    environment:
      - PORT=3000
    ports:
      - '8003:3000'
    volumes:
      - ./apps/nest/:/home/node/app
    command: 'bash -c "npm install && npm run build && npm run start:prod"'
  laravel-octane:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - "8004:8000"
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: "1"
    volumes:
      - ./apps/laravel/:/var/www/html
    command: 'php artisan octane:start --server=frankenphp --host=0.0.0.0 --workers=10 --task-workers=10'

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'stress'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql:rw
