version: '3.8'
services:
  laravel:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - "14001:8000"
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: "1"
    volumes:
      - ./apps/laravel/:/var/www/html
    command: 'bash -c "composer install && php artisan migrate --force && php artisan serve --host=0.0.0.0"'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  symfony:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - "14002:8000"
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: "1"
    volumes:
      - ./apps/symfony/:/var/www/html
    command: 'bash -c "composer install && php -S 0.0.0.0:8000 -t public"'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  express:
    image: "node:20"
    working_dir: /home/node/app
    environment:
      - PORT=3000
    ports:
      - '14003:3000'
    volumes:
      - ./apps/express/:/home/node/app
    command: 'bash -c "npm install && npm run start"'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  nest:
    image: "node:20"
    working_dir: /home/node/app
    environment:
      - PORT=3000
    ports:
      - '14004:3000'
    volumes:
      - ./apps/nest/:/home/node/app
    command: 'bash -c "npm install && npm run build && npm run start:prod"'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  laravel-octane:
    image: serversideup/php:8.3-fpm-nginx
    ports:
      - "14005:8000"
    environment:
      SSL_MODE: "off"
      PHP_OPCACHE_ENABLE: "1"
    volumes:
      - ./apps/laravel/:/var/www/html
    command: 'bash -c "php artisan octane:start --server=frankenphp --host=0.0.0.0 --workers=10 --task-workers=10"'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'stress'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/var/lib/mysql:rw
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
